# Generated by Django 4.2.13 on 2026-01-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_verification_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='otp_verific_email_621537_idx',
            old_name='otp_verification_email_type_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='otp_verific_phone_b075d4_idx',
            old_name='otp_verification_phone_type_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='otp_verific_is_veri_916af0_idx',
            old_name='otp_verification_status_idx',
        ),
    ]
