# Generated by Django 4.2.13 on 2026-05-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_about_me_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomineeAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('death', 'User Deceased'), ('medical', 'Medical Emergency'), ('accident', 'Accident'), ('unreachable', 'Unable to Reach'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('user_notified', 'User Notified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('access_granted', 'Access Granted')], default='pending', max_length=20)),
                ('user_response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('access_granted_at', models.DateTimeField(blank=True, null=True)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='accounts.nominee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nominee_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('check_in_interval', models.IntegerField(choices=[(10, '10 Days'), (15, '15 Days'), (20, '20 Days'), (30, '30 Days'), (45, '45 Days'), (60, '60 Days')], default=30)),
                ('grace_period', models.IntegerField(choices=[(3, '3 Days'), (5, '5 Days'), (7, '7 Days'), (10, '10 Days'), (14, '14 Days')], default=7)),
                ('missed_checkins_for_reminder', models.IntegerField(default=1)),
                ('missed_checkins_for_urgent', models.IntegerField(default=2)),
                ('missed_checkins_for_emergency', models.IntegerField(default=3)),
                ('auto_trigger_emergency', models.BooleanField(default=True)),
                ('notify_nominees_on_missed', models.BooleanField(default=True)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('next_check_in_due', models.DateTimeField(blank=True, null=True)),
                ('is_emergency_triggered', models.BooleanField(default=False)),
                ('emergency_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_access_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Emergency Settings',
                'db_table': 'emergency_settings',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('reminder', 'Check-in Reminder'), ('urgent', 'Urgent Alert'), ('emergency', 'Emergency Triggered'), ('access_unlocked', 'Access Unlocked'), ('nominee_request', 'Nominee Access Request')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=10)),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_type', models.CharField(choices=[('user', 'User'), ('nominee', 'Nominee')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed'), ('auto', 'Automatic')], default='on_time', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'check_in_records',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
