# Generated by Django 4.2.13 on 2026-05-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_nomineeaccessrequest_emergencysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='emergency_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_records', to='accounts.emergencysettings'),
        ),
    ]
