# Generated by Django 4.2.13 on 2026-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_checkinrecord_emergency_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='can_add_nominees',
            field=models.BooleanField(default=False),
        ),
    ]
