# Generated by Django 4.2.13 on 2026-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_nominee_can_add_nominees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='access_level',
            field=models.CharField(choices=[('view', 'View Only'), ('download', 'View and Download'), ('notes', 'Notes Only'), ('full', 'Full Access')], default='view', max_length=10),
        ),
    ]
