# Generated by Django 4.2 on 2026-01-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('inactivity', 'Inactivity Period'), ('manual', 'Manual Emergency Button'), ('scheduled', 'Scheduled Date')], max_length=20)),
                ('inactivity_days', models.IntegerField(blank=True, default=90, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('require_mfa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_triggers',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to='accounts.nominee')),
                ('trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='emergency.emergencytrigger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_access_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_accesses',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed Document'), ('download', 'Downloaded Document'), ('access_instructions', 'Accessed Instructions'), ('login', 'Login Attempt'), ('logout', 'Logout')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.document')),
                ('emergency_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emergency.emergencyaccess')),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
