# Generated by Django 4.2 on 2026-01-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vault.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_key_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('total_documents', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vaults',
            },
        ),
        migrations.CreateModel(
            name='EmergencyInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_message', models.TextField(blank=True, null=True)),
                ('medical_consent', models.TextField(blank=True, null=True)),
                ('family_guidance', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Emergency Instructions',
                'db_table': 'emergency_instructions',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('id', 'ID Documents'), ('medical', 'Medical Records'), ('insurance', 'Insurance'), ('property', 'Property Documents'), ('financial', 'Financial Documents'), ('legal', 'Legal Documents'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=vault.models.user_directory_path)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_metadata', models.JSONField(blank=True, default=dict)),
                ('is_accessible_by_nominee', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reminder_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vault.vault')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
