# Generated by Django 4.2.13 on 2026-05-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Site Statistics',
            },
        ),
    ]
